name: shopify
description: A Flutter shopify using FakeStore API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - asset: assets/fonts/Poppins-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/Poppins-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Poppins-Light.ttf
#          weight: 300